name: Check Citation Format
on:
  push:
    paths:
      - CITATION.cff
  pull_request:
    paths:
      - CITATION.cff
jobs:
  check-citation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
