name: Check Python Linting and Tests

on: [push, pull_request]

jobs:
  stac-model:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: make poetry-install

    - name: Set up cache
      uses: actions/cache@v4.0.2
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: make install-dev

    - name: Run checks
      run: |
        make lint-all

    - name: Run tests
      run: |
        make test
